from app.schemas.institution import (
    InstitutionCreate,
    InstitutionUpdate,
    InstitutionRead,
    AcademicYearCreate,
    AcademicYearUpdate,
    AcademicYearRead,
    DayOfWeekCreate,
    DayOfWeekUpdate,
    DayOfWeekRead,
    PeriodCreate,
    PeriodUpdate,
    PeriodRead,
)

from app.schemas.building import (
    BuildingCreate,
    BuildingUpdate,
    BuildingRead,
    BuildingWithRooms,
    RoomCreate,
    RoomUpdate,
    RoomRead,
)

from app.schemas.subject import (
    SubjectCreate,
    SubjectUpdate,
    SubjectRead,
    ActivityTagCreate,
    ActivityTagUpdate,
    ActivityTagRead,
)

from app.schemas.teacher import (
    TeacherCreate,
    TeacherUpdate,
    TeacherRead,
)

from app.schemas.student import (
    StudentYearCreate,
    StudentYearUpdate,
    StudentYearRead,
    StudentGroupCreate,
    StudentGroupUpdate,
    StudentGroupRead,
    StudentSubgroupCreate,
    StudentSubgroupUpdate,
    StudentSubgroupRead,
    StudentGroupWithSubgroups,
    StudentYearWithGroups,
)

from app.schemas.activity import (
    ActivityCreate,
    ActivityUpdate,
    ActivityRead,
    ActivityWithRelations,
)

from app.schemas.constraint import (
    TeacherNotAvailableCreate,
    TeacherNotAvailableUpdate,
    TeacherNotAvailableRead,
    TeacherMaxHoursDailyCreate,
    TeacherMaxHoursDailyUpdate,
    TeacherMaxHoursDailyRead,
    TeacherMaxHoursWeeklyCreate,
    TeacherMaxHoursWeeklyUpdate,
    TeacherMaxHoursWeeklyRead,
    TeacherMaxGapsDailyCreate,
    TeacherMaxGapsDailyUpdate,
    TeacherMaxGapsDailyRead,
    TeacherMaxGapsWeeklyCreate,
    TeacherMaxGapsWeeklyUpdate,
    TeacherMaxGapsWeeklyRead,
    StudentsMaxHoursDailyCreate,
    StudentsMaxHoursDailyUpdate,
    StudentsMaxHoursDailyRead,
    StudentsMaxHoursWeeklyCreate,
    StudentsMaxHoursWeeklyUpdate,
    StudentsMaxHoursWeeklyRead,
    StudentsMaxGapsDailyCreate,
    StudentsMaxGapsDailyUpdate,
    StudentsMaxGapsDailyRead,
    StudentsMaxGapsWeeklyCreate,
    StudentsMaxGapsWeeklyUpdate,
    StudentsMaxGapsWeeklyRead,
    ActivityPreferredStartingTimeCreate,
    ActivityPreferredStartingTimeUpdate,
    ActivityPreferredStartingTimeRead,
    ActivityPreferredStartingDayCreate,
    ActivityPreferredStartingDayUpdate,
    ActivityPreferredStartingDayRead,
    ActivitiesNotOnSameDayCreate,
    ActivitiesNotOnSameDayUpdate,
    ActivitiesNotOnSameDayRead,
    ActivitiesConsecutiveCreate,
    ActivitiesConsecutiveUpdate,
    ActivitiesConsecutiveRead,
    ActivitiesSameStartingTimeCreate,
    ActivitiesSameStartingTimeUpdate,
    ActivitiesSameStartingTimeRead,
    ActivitiesSameStartingDayCreate,
    ActivitiesSameStartingDayUpdate,
    ActivitiesSameStartingDayRead,
    RoomNotAvailableCreate,
    RoomNotAvailableUpdate,
    RoomNotAvailableRead,
)

from app.schemas.solve_job import (
    SolveJobCreate,
    SolveJobRead,
    SolveProgress,
    Assignment,
)

__all__ = [
    # Institution
    "InstitutionCreate",
    "InstitutionUpdate",
    "InstitutionRead",
    "AcademicYearCreate",
    "AcademicYearUpdate",
    "AcademicYearRead",
    "DayOfWeekCreate",
    "DayOfWeekUpdate",
    "DayOfWeekRead",
    "PeriodCreate",
    "PeriodUpdate",
    "PeriodRead",
    # Building
    "BuildingCreate",
    "BuildingUpdate",
    "BuildingRead",
    "BuildingWithRooms",
    "RoomCreate",
    "RoomUpdate",
    "RoomRead",
    # Subject
    "SubjectCreate",
    "SubjectUpdate",
    "SubjectRead",
    "ActivityTagCreate",
    "ActivityTagUpdate",
    "ActivityTagRead",
    # Teacher
    "TeacherCreate",
    "TeacherUpdate",
    "TeacherRead",
    # Student
    "StudentYearCreate",
    "StudentYearUpdate",
    "StudentYearRead",
    "StudentGroupCreate",
    "StudentGroupUpdate",
    "StudentGroupRead",
    "StudentSubgroupCreate",
    "StudentSubgroupUpdate",
    "StudentSubgroupRead",
    "StudentGroupWithSubgroups",
    "StudentYearWithGroups",
    # Activity
    "ActivityCreate",
    "ActivityUpdate",
    "ActivityRead",
    "ActivityWithRelations",
    # Constraints
    "TeacherNotAvailableCreate",
    "TeacherNotAvailableUpdate",
    "TeacherNotAvailableRead",
    "TeacherMaxHoursDailyCreate",
    "TeacherMaxHoursDailyUpdate",
    "TeacherMaxHoursDailyRead",
    "TeacherMaxHoursWeeklyCreate",
    "TeacherMaxHoursWeeklyUpdate",
    "TeacherMaxHoursWeeklyRead",
    "TeacherMaxGapsDailyCreate",
    "TeacherMaxGapsDailyUpdate",
    "TeacherMaxGapsDailyRead",
    "TeacherMaxGapsWeeklyCreate",
    "TeacherMaxGapsWeeklyUpdate",
    "TeacherMaxGapsWeeklyRead",
    "StudentsMaxHoursDailyCreate",
    "StudentsMaxHoursDailyUpdate",
    "StudentsMaxHoursDailyRead",
    "StudentsMaxHoursWeeklyCreate",
    "StudentsMaxHoursWeeklyUpdate",
    "StudentsMaxHoursWeeklyRead",
    "StudentsMaxGapsDailyCreate",
    "StudentsMaxGapsDailyUpdate",
    "StudentsMaxGapsDailyRead",
    "StudentsMaxGapsWeeklyCreate",
    "StudentsMaxGapsWeeklyUpdate",
    "StudentsMaxGapsWeeklyRead",
    "ActivityPreferredStartingTimeCreate",
    "ActivityPreferredStartingTimeUpdate",
    "ActivityPreferredStartingTimeRead",
    "ActivityPreferredStartingDayCreate",
    "ActivityPreferredStartingDayUpdate",
    "ActivityPreferredStartingDayRead",
    "ActivitiesNotOnSameDayCreate",
    "ActivitiesNotOnSameDayUpdate",
    "ActivitiesNotOnSameDayRead",
    "ActivitiesConsecutiveCreate",
    "ActivitiesConsecutiveUpdate",
    "ActivitiesConsecutiveRead",
    "ActivitiesSameStartingTimeCreate",
    "ActivitiesSameStartingTimeUpdate",
    "ActivitiesSameStartingTimeRead",
    "ActivitiesSameStartingDayCreate",
    "ActivitiesSameStartingDayUpdate",
    "ActivitiesSameStartingDayRead",
    "RoomNotAvailableCreate",
    "RoomNotAvailableUpdate",
    "RoomNotAvailableRead",
    # Solve Job
    "SolveJobCreate",
    "SolveJobRead",
    "SolveProgress",
    "Assignment",
]
